:!outline:

== Sergei Kartin

=== Senior Front End Engineer | Full Stack Engineer

Budva, Montenegro | sergei.kartin@gmail.com | https://linkedin.com/in/sergeikartin[LinkedIn] | https://github.com/sergeikartin[GitHub]


Highly experienced software engineer with over 17 years of professional expertise in both backend and frontend development, proficient in TypeScript, React, and Node.js. 
Known for exceptional problem-solving abilities, keen attention to detail, adaptability, and a dedication to continuous learning.



=== Skills
*Languages*: HTML, CSS, JavaScript, TypeScript, Java

*Technologies*: React, GraphQL, Node.js, React Query, Tailwind CSS, Next.js, Vite, Vitest, Yarn


=== Experience

*https://bettermode.com/[Bettermode], Remote | Front End Engineer* +
Sep 2020 - Feb 2024

In addition to delivering product and consumer-facing features of the platform, I also +

- Developed and maintained a UI kit using React and Tailwind, streamlining frontend development for a team of 5-10 developers
- Established a design system with theming and dark mode support, improving UI consistency and customizability
- Improved front-end developer experience by migrating from Webpack + React 16 to Vite + React 18, reducing HMR performance from >30s to instant module replacements and cutting initial bundle size by 50%

*https://toptal.com/[Toptal], Remote | JavaScript developer* +
2018 - 2020

Developed a Facebook Messenger chat bot for prospective students of University of Sydney using Botkit, enhancing engagement by automating responses to common inquiries

*https://listingloop.com.au/[ListingLoop], Remote | Front End Engineer* +
Jun 2018 - Jul 2019

Developed an MVP product for the Australian real estate market using Firebase, React, and Redux, successfully achieving a $500K crowdfunding target within three months

*https://www.azoft.com/[Azoft], Novosibirsk | Senior Java Developer | Tech Lead* +
Mar 2017 – Jun 2018

- Led a team of 5 engineers to develop an MVP for a financial social network integrated with online banking
- Refactored the Customer Loyalty Program web app for a top 5 Russian bank, enhancing scalability and enabling deployment in two additional banks
- Technologies: Java, Kotlin, Spring Boot, Spring Data, PostgreSQL


*Easysport, Remote | Senior Java Developer* +
2010 – 2017

Led the development of web application for booking sport courts in team of 5-7 developers using Java, EJB, JSF


*Softage, Novosibirsk | Java Developer | Software Developer* +
2008 – 2010

Developed new features for JavaEE customer engagement improvement solution +
- Created a standalone tool for populating database used for performance tests


=== Education
Bachelor's degree in IT | Novosibirsk State University, 2007


=== Languages
- Russian (Native)
- English (Full professional proficiency)
- Spanish (Intermediate level)
